spring:
  profiles:
    active: dev
  mvc:
    view:
      suffix: /WEB-INF/templates/
      prefix: .jsp
logging:
  config: classpath:logback-spring.xml

---
spring:
  profiles: dev

server:
  port: 8080


---
spring:
  profiles: pro

server:
  port: 8082
